#!/usr/bin/env bash
#ddev-generated

## Description: Create and destroy solr cores and configsets
## Usage: kcctl <realm>
## Example: ddev kcctl

# push to ./keycloak/import:/opt/keycloak/data/import
# docker cp -q "$config" ddev-"$DDEV_SITENAME"-apache-solr:/var/solr/data/

# docker run -it --rm -v ./keycloak/import:/opt/keycloak/data/import --mount source=ddev-typo3-cloud_keycloak-db,destination=/opt/keycloak/data quay.io/keycloak/keycloak:23.0 export $@ --dir /opt/keycloak/data/import

CONTAINER_NAME=ddev-"$DDEV_SITENAME"-keycloak

CMD=$1
case $CMD in
import)
    # Copy files to the keycloak volume
    import_data=".ddev/keycloak/import"
    echo "➡️ Copy '$import_data' to container and import data"
    docker cp -q "$import_data/." "$CONTAINER_NAME:/opt/keycloak/data/import"
    docker exec -i "$CONTAINER_NAME" rm -Rf /opt/keycloak/data/h2
    docker restart "$CONTAINER_NAME" 1>/dev/null
    ;;

export)
    REALM=""
    if [ -n "$2" ]; then
        REALM="--realm $2"
    fi

    if [ "$2" = "master" ]; then
        echo "'master' is not exported because it is the default realm. Please use the 'ddev' realm or any other you want to export."
        exit 0
    fi

    export_data=".ddev/keycloak/import"
    ddev exec -s keycloak rm -Rf "/opt/keycloak/data/import/$2*"
    ddev exec -s keycloak /opt/keycloak/bin/kc.sh export --users same_file "$REALM" --dir /opt/keycloak/data/import
    ddev exec -s keycloak rm -Rf "/opt/keycloak/data/import/master*"
    docker cp -q "$CONTAINER_NAME:/opt/keycloak/data/import/." "$export_data/"
    ;;

delete)
    echo "➡️ Delete database and configuration in container"
    docker exec -u 0 -i "$CONTAINER_NAME" rm -Rf /opt/keycloak/data/*
    docker restart "$CONTAINER_NAME" 1>/dev/null
    ;;

--help | *)
    echo "——————————————"
    echo -e "\033[1mExample Usage:\033[0m"
    echo "——————————————"
    echo -e "\033[1mApply\033[0m"
    echo "—————"
    echo "Create push config to keycloak and import it"
    echo "👉 ddev kcctl apply [config path] - relative to docroot, optional"
    echo ""
    echo -e "\033[1mWipe\033[0m"
    echo "—————"
    echo "Delete all realms and users"
    echo "👉 ddev kcctl wipe"
    ;;
esac
